distributable:
  url: https://github.com/laravel/installer/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: laravel/installer

dependencies:
  php.net: ^8.2
  getcomposer.org: ^2.7
  linux:
    info-zip.org/unzip: ^6

build:
  - composer install --no-dev
  - mkdir -p {{prefix}}/libexec
  - cp -r ./* {{prefix}}/libexec
  - run: ln -s ../libexec/bin/laravel laravel
    working-directory: ${{prefix}}/bin

provides:
  - bin/laravel

test:
  dependencies:
    curl.se: '*'
    pkgx.sh: ^1
  script:
    - laravel --version | grep {{version}}
    - laravel new blog --no-interaction
    - cd blog
    # FIXME: this is producing some weird errors on linux/x86-64:
    # /opt/php.net/v8.3.11/bin/php: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/php.net/v8.3.11/bin/php)
    - pkgx +php.net +gnu.org/gcc/libstdcxx php artisan serve --port=$PORT | tee server.log &
    - PID=$!
    - sleep 5
    - curl http://localhost:$PORT
    - curl -s http://localhost:$PORT | grep Laravel
    - kill $PID
    - grep 'Server running' server.log
  env:
    PORT: $(pkgx get-port | tail -n1)
