distributable:
  url: https://github.com/MilesCranmer/rip2/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

display-name: rip2

versions:
  github: MilesCranmer/rip2

build:
  dependencies:
    rust-lang.org: ">=1.75"
    rust-lang.org/cargo: "*"
  script: cargo install $ARGS
  env:
    ARGS:
      - --locked
      - --path=.
      - --root {{prefix}}

provides:
  - bin/rip

test: rip --version
