distributable:
  url: https://github.com/alacritty/alacritty/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

display-name: https://alacritty.org/

versions:
  github: alacritty/alacritty

dependencies:
  freedesktop.org/fontconfig: "*"
  freetype.org: 2
  xkbcommon.org: '*'
  x.org/xcb: ^1

build:
  dependencies:
    rust-lang.org: ">=1.75"
    rust-lang.org/cargo: "*"
  script: |
    cargo install $ARGS
  env:
    ARGS:
      - --locked
      - --path=alacritty
      - --root {{prefix}}

provides:
  - bin/alacritty

test:
  script: |
    alacritty --version
